name:                squeal
version:             0.1.0.6
github:              "ssanj/squeal"
license:             BSD3
author:              "sanjiv sahayam"
maintainer:          "sanjsmailbox@gmail.com"
copyright:           "(c) 2017 sanjiv sahayam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ssanj/squeal#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- http-client
- http-client-tls
- http-types
- case-insensitive
- aeson
- cryptonite

library:
  source-dirs: src
  other-modules: Paths_squeal
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

executables:
  squeal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    dependencies:
    - squeal

tests:
  squeal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    dependencies:
    - squeal
